wandb_version: 1

batch:
  desc: null
  value: 8
epochs:
  desc: null
  value: 50
imgsz:
  desc: null
  value: 512
lr0:
  desc: null
  value: 0.00013341876445302774
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743418223.587657
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 2
      - 13
      - 23
      - 37
      4: 3.11.11
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
