_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 80
                - 105
            "2":
                - 1
                - 41
                - 49
                - 55
                - 80
                - 105
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch:
    value: 16
epochs:
    value: 50
imgsz:
    value: 416
lr0:
    value: 0.007802886542220457
optimizer:
    value: Adam
